guest_book/apps/book/urls.py
from django.conf.urls import patterns, url

from .views import MessageBoardView


urlpatterns = patterns('',
                       url(r'^$', MessageBoardView.as_view(), name='board'),
                       url(r'(?P<page>\d+)/$', MessageBoardView.as_view(), name='board_page'),
                       )

guest_book/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'guest_book.apps.book.views.index_redirect',
                           name='index_redirect'),
                       url(r'^board/', include('guest_book.apps.book.urls',
                                               namespace='book',
                                               app_name='book')),
                       url(r'^admin/', include(admin.site.urls)),
                      )

guest_book/apps/book/models.py
from django.utils import timezone
from django.db import models
import postmarkup


class Message(models.Model):
    username = models.CharField(max_length=30)
    user_email = models.EmailField()
    message_text = models.TextField(max_length=500)
    pub_date = models.DateTimeField()
    user_homepage = models.URLField(blank=True)
    user_addr = models.GenericIPAddressField(blank=True, null=True)
    user_browser = models.CharField(max_length=100, blank=True)

    ALLOWED_MARKUP = ['b', 's', 'u', 'i']  # Allowed BBCodes

    class Meta:
        verbose_name_plural = 'Messages'
        ordering = ['-pub_date']

    def save(self, **kwargs):
        self.pub_date = timezone.now()
        self.message_text = self.convert_message_text(self.message_text)
        super(Message, self).save(**kwargs)

    def __unicode__(self):
        return "{name} | {email} | {date}".format(name=self.username,
                                                  email=self.user_email,
                                                  date=self.pub_date)

    def convert_message_text(self, message_text):
        class MyLinkTag(postmarkup.LinkTag):
            """
            Overrides annotate_link behavior in LinkTag
            """
            def __init__(self, name, **kwargs):
                postmarkup.LinkTag.__init__(self, name,
                                            annotate_links=False, **kwargs)

        markup = postmarkup.create(include=self.ALLOWED_MARKUP,
                                   use_pygments=False)
        markup.add_tag(MyLinkTag, u'url')
        return markup(message_text)

guest_book/apps/book/forms.py
import re

from django import forms
from captcha.fields import ReCaptchaField


class MessageForm(forms.Form):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs=\
                                        {'placeholder': 'Enter your name',
                                         'class': 'form-control input-sm'})
                               )
    email = forms.EmailField(max_length=100,
                             widget=forms.TextInput(attrs=\
                                        {'placeholder': 'Enter your email',
                                         'class': 'form-control input-sm'})
                             )
    homepage = forms.URLField(required=False, max_length=100,
                              widget=forms.TextInput(attrs=\
                                        {'placeholder': 'You may enter your site address',
                                         'class': 'form-control input-sm'})
                             )
    message_body = forms.CharField(max_length=750, min_length=1,
                                   widget=forms.Textarea(attrs=\
                                        {'id':'comment',
                                         'placeholder': 'Enter your message',
                                         'class': 'form-control input-sm',
                                         'rows': '4'})
                                  )
    captcha = ReCaptchaField(attrs={'theme': 'clean'})

    def clean_message_body(self):
        data = self.cleaned_data['message_body']
        # check if message totally consists of space characters
        # (spaces, line breaks)
        match = re.search(r'^\s+$', data)
        if match:
            raise forms.ValidationError("Please left us something more "
                                        "meaningful than blank message")
        return data

guest_book/apps/book/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic.edit import FormView
from django.core.paginator import Paginator, EmptyPage

import httpagentparser
from .forms import MessageForm
from .models import Message


def index_redirect(request):
    return redirect(reverse('book:board'))


class MessageBoardView(FormView):
    template_name = "book/message_board.html"
    form_class = MessageForm
    success_url = reverse_lazy('book:board')
    paginate_messages_by = 10

    def form_valid(self, form):
        data = form.cleaned_data
        user_addr = self.request.META.get('REMOTE_ADDR', '')
        try:
            user_agent = self.request.META['HTTP_USER_AGENT']
            info = httpagentparser.detect(user_agent)
            user_browser = info['browser']['name']
            data['user_browser'] = user_browser
        except KeyError:
            pass
        Message.objects.create(username=data['username'],
                               user_email=data['email'],
                               message_text=data['message_body'],
                               user_homepage=data['homepage'],
                               user_addr=user_addr,
                               user_browser=data.get('user_browser', '')
                               )
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(FormView, self).get_context_data(**kwargs)
        messages = Message.objects.all()
        paginator = Paginator(messages, self.paginate_messages_by)
        # if no page provided return the first page
        index = int(self.kwargs.get('page', 1))
        try:
            page = paginator.page(index)
        except EmptyPage:
            # if requested page is out of range, deliver the last page
            page = paginator.page(paginator.num_pages)
        context['page'] = page
        context['page_numbers'] = paginator.page_range

        return context

guest_book/templates/book/message_board.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome</title>
    {% load static from staticfiles %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'js/bbcodes.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h3>Wait! Have you ever seen 2-columns guest book?</h3>
            </div>
        </div>
        <div class="row">
            <!--Left column, list of messages on the board-->
            <div class="col-lg-6">
                <!--Pagination links-->
                <div class="row">
                    <ul class="pagination">
                        {% if page.has_previous %}
                            <li><a href="{% url 'book:board_page' page=page.previous_page_number %}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><a>&laquo;</a></li>
                        {% endif %}
                        {% for index in page_numbers %}
                            <li {% ifequal index page.number %}class="active"{% endifequal %}>
                                <a href="{% url 'book:board_page' page=index %}">{{ index }}</a>
                            </li>
                        {% endfor %}
                        {% if page.has_next %}
                            <li><a href="{% url 'book:board_page' page=page.next_page_number %}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><a>&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
                <!--End pagination-->
                <!--Board messages themselves-->
                <div class="row">
                    <ul class="media-list">
                        {% for message in page %}
                            <li class="media">
                                <!--<a class="pull-left" href="#">-->
                                  <!--<img class="media-object" src="" alt="">-->
                                <!--</a>-->
                                <div class="media-body">
                                    <h5 class="media-heading">
                                        <strong>{{ message.username }}</strong> |
                                        <strong>{{ message.user_email }}</strong> |
                                        <strong>{{ message.pub_date }}</strong>
                                        {% if message.user_homepage %}
                                            | <strong>{{ message.user_homepage }}</strong>
                                        {% endif %}
                                    </h5>
                                    <span class="message_body">{{ message.message_text|safe }}</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--End board messages-->
            </div>
            <!--End left column-->
            <!--Right column, form to add messages on the board-->
            <div class="col-lg-6">
                <form role="form" class="form-horizontal" action="{% url 'book:board' %}" method="post">
                    <h3><span class="label label-default">Left us your meaningful opinion</span></h3>
                    <div class="form-group">
                        <div class="col-sm-6 {% if form.errors.username %}has-error{% endif %}">
                            <label for="id_username">Name *</label>
                            {{ form.username }}
                        </div>
                        <div class="col-sm-6">
                            <p class="help-inline h6">{{ form.username.errors.as_text}}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6 {% if form.errors.email %}has-error{% endif %}">
                            <label for="id_email">E-mail *</label>
                            {{ form.email }}
                        </div>
                        <div class="col-xs-6">
                            <p class="help-block h6">{{ form.email.errors.as_text }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6 {% if form.errors.homepage %}has-error{% endif %}">
                            <label for="id_homepage">Homepage</label>
                            {{ form.homepage }}
                        </div>
                        <div class="col-xs-6">
                            <p class="help-block h6">{{ form.homepage.errors|striptags }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-9 {% if form.errors.message_body %}has-error{% endif %}">
                            <label for="id_message_body">Message text *</label>
                            <div class="actions">
                                <img src="{% static 'images/icons/bold.gif' %}" onClick="setCommentText('comment', 'bold');"/>
                                <img src="{% static 'images/icons/italic.gif' %}" onClick="setCommentText('comment', 'italic');"/>
                                <img src="{% static 'images/icons/underline.gif' %}" onClick="setCommentText('comment', 'underline');"/>
                            </div>
                            {{ form.message_body }}
                        </div>
                        <div class="col-xs-3">
                            <p class="help-block h6">{{ form.message_body.errors.as_text }}</p>
                        </div>
                    </div>
                    <!--<p class="help-block">* These fields are required</p>-->
                    <div class="form-group">
                        <div class="col-xs-10">
                            {{ form.captcha }}
                        </div>
                        <div class="col-xs-2">
                            <p class="help-block h6">{{ form.captcha.errors.as_text }}</p>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-default" value="Submit">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>

</body>
</html>